# Generated by Django 4.2 on 2023-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdata',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='birthdata',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='birthdata',
            name='minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='birthdata',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='birthdata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
