# Generated by Django 4.2 on 2023-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdata', '0002_alter_birthdata_date_alter_birthdata_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdata',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='birthdata',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
