# Generated by Django 4.2 on 2023-04-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdata', '0003_alter_birthdata_latitude_alter_birthdata_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdata',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
        migrations.AlterField(
            model_name='birthdata',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
    ]
